language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --dev --no-interaction
  - composer dumpautoload

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-text